/**
 * Repomix adapter for cx CLI
 *
 * Responsibilities:
 *  - Scan a bundle folder containing repomix output files and binary assets
 *  - Compute streaming SHA256 and file metadata (size, line count, binary detection)
 *  - Write manifest.json and SHA256SUMS to the bundle folder
 *  - Optionally produce a .zip archive of the bundle (streamed via archiver)
 *  - Parse repomix output files (XML or JSON) to enumerate contained source files
 *  - Remove generated artefacts during cleanup
 *
 * Design notes:
 *  - Requires Node.js >= 20 and ESM.
 *  - All manifest entries are sorted deterministically by path.
 *  - ZIP creation streams directly to disk; no full-archive buffering.
 */

import crypto from 'node:crypto';
import { createReadStream, createWriteStream } from 'node:fs';
import fsPromises from 'node:fs/promises';
import path from 'node:path';
import { pipeline } from 'node:stream/promises';

import archiver from 'archiver';
import fg from 'fast-glob';
import { XMLParser } from 'fast-xml-parser';

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export type FileEntry = {
  /** Relative path inside the bundle folder (posix separators). */
  path: string;
  /** File size in bytes. */
  size: number;
  /** Number of lines (text files only). */
  lines?: number;
  /** SHA-256 hex digest. */
  sha256: string;
  /** Whether the file is treated as binary. */
  isBinary: boolean;
};

export type BundleManifest = {
  /** Manifest format version. */
  format: string;
  /** ISO 8601 creation timestamp. */
  createdAt: string;
  /** Tool that produced this manifest. */
  createdBy: string;
  /** Repomix output files found in the bundle. */
  repomixFiles: FileEntry[];
  /** Additional binary and text assets found in the bundle. */
  assets: FileEntry[];
  /** Arbitrary extra metadata. */
  metadata: Record<string, unknown>;
};

/** A single source-file entry extracted from a repomix output file. */
export type RepomixEntry = {
  /** Source path as recorded inside the repomix output. */
  path: string;
  /** Character count if available. */
  charCount?: number;
};

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/** Well-known plain-text extensions — used to skip binary-sniffing. */
const TEXT_EXTENSIONS = new Set([
  '.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs',
  '.json', '.jsonc', '.json5',
  '.md', '.markdown', '.txt', '.rst',
  '.html', '.htm', '.css', '.scss', '.sass', '.less',
  '.yaml', '.yml', '.toml', '.ini', '.env',
  '.xml', '.svg',
  '.sh', '.bash', '.zsh', '.fish',
  '.dockerfile', '.gitignore', '.gitattributes',
  '.lock',
]);

/** Returns true when the file is likely binary. */
async function isProbablyBinary(filePath: string): Promise<boolean> {
  const ext = path.extname(filePath).toLowerCase();
  if (ext && TEXT_EXTENSIONS.has(ext)) return false;

  try {
    const fd = await fsPromises.open(filePath, 'r');
    const buffer = Buffer.alloc(4096);
    const { bytesRead } = await fd.read(buffer, 0, 4096, 0);
    await fd.close();
    for (let i = 0; i < bytesRead; i++) {
      if (buffer[i] === 0) return true;
    }
    return false;
  } catch {
    return true; // conservative fallback
  }
}

/** Computes SHA-256 digest of a file using streaming. */
async function sha256File(filePath: string): Promise<string> {
  const hash = crypto.createHash('sha256');
  const readable = createReadStream(filePath);
  for await (const chunk of readable) {
    hash.update(chunk as Buffer);
  }
  return hash.digest('hex');
}

/** Counts newlines in a text file using streaming. */
async function countLines(filePath: string): Promise<number> {
  let newlines = 0;
  const readable = createReadStream(filePath, { encoding: 'utf8' });
  for await (const chunk of readable) {
    for (let i = 0; i < (chunk as string).length; i++) {
      if ((chunk as string)[i] === '\n') newlines++;
    }
  }
  return newlines;
}

/** Converts an OS path to posix separators. */
function toPosix(p: string): string {
  return p.split(path.sep).join('/');
}

// ---------------------------------------------------------------------------
// Pattern constants
// ---------------------------------------------------------------------------

/** Glob patterns that identify repomix output files by name. */
const REPOMIX_OUTPUT_PATTERNS = [
  /^repomix-output(\.(xml|json|txt|md))?$/i,
  /^repomix-output[-_].+\.(xml|json|txt|md)$/i,
  /repomix.*output/i,
];

function isRepomixOutput(relPath: string): boolean {
  const base = path.basename(relPath);
  return REPOMIX_OUTPUT_PATTERNS.some(re => re.test(base));
}

/** Files generated by cx itself — excluded when scanning. */
const GENERATED_FILE_NAMES = new Set(['manifest.json', 'SHA256SUMS']);

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Scans a bundle folder and returns an (unsaved) manifest object.
 *
 * @param bundlePath  Absolute or relative path to the bundle folder.
 * @param opts        Optional scan configuration.
 */
export async function scanBundleFolder(
  bundlePath: string,
  opts: { includeHidden?: boolean; exclude?: string[] } = {},
): Promise<BundleManifest> {
  const root = path.resolve(bundlePath);
  const ignore = opts.exclude ?? ['**/node_modules/**', '**/.git/**'];

  const relPaths = await fg('**/*', {
    cwd: root,
    dot: opts.includeHidden ?? false,
    ignore,
    onlyFiles: true,
    followSymbolicLinks: false,
  });

  const repomixFiles: FileEntry[] = [];
  const assets: FileEntry[] = [];

  for (const rel of relPaths.sort()) {
    // Skip cx-generated artefacts so repeated runs stay idempotent.
    if (GENERATED_FILE_NAMES.has(path.basename(rel))) continue;
    // Skip zip archives generated by cx.
    if (rel.endsWith('.bundle.zip')) continue;

    const abs = path.join(root, rel);
    const stat = await fsPromises.stat(abs);
    const binary = await isProbablyBinary(abs);
    const digest = await sha256File(abs);

    const entry: FileEntry = {
      path: toPosix(rel),
      size: stat.size,
      sha256: digest,
      isBinary: binary,
      ...(binary ? {} : { lines: await countLines(abs) }),
    };

    if (isRepomixOutput(rel)) {
      repomixFiles.push(entry);
    } else {
      assets.push(entry);
    }
  }

  return {
    format: 'cx-bundle/v1',
    createdAt: new Date().toISOString(),
    createdBy: 'cx-cli',
    repomixFiles,
    assets,
    metadata: {},
  };
}

/**
 * Writes `manifest.json` and `SHA256SUMS` into the bundle folder.
 *
 * @param bundlePath  Path to the bundle folder.
 * @param manifest    Manifest object produced by {@link scanBundleFolder}.
 */
export async function writeManifestAndSha(
  bundlePath: string,
  manifest: BundleManifest,
): Promise<void> {
  const root = path.resolve(bundlePath);

  // manifest.json
  const manifestJson = JSON.stringify(manifest, null, 2) + '\n';
  await fsPromises.writeFile(path.join(root, 'manifest.json'), manifestJson, 'utf8');

  // SHA256SUMS (sha256sum-compatible format)
  const allEntries = [...manifest.repomixFiles, ...manifest.assets];
  const lines = allEntries
    .sort((a, b) => a.path.localeCompare(b.path))
    .map(e => `${e.sha256}  ${e.path}`)
    .join('\n');
  await fsPromises.writeFile(
    path.join(root, 'SHA256SUMS'),
    lines + '\n',
    'utf8',
  );
}

/**
 * Creates a deterministic ZIP archive of the entire bundle folder.
 *
 * Files are streamed directly to `outputZipPath`; the bundle folder is
 * not buffered in memory as a whole.
 *
 * @param bundlePath     Source bundle folder.
 * @param outputZipPath  Destination ZIP file path.
 */
export async function createZipFromBundleFolder(
  bundlePath: string,
  outputZipPath: string,
): Promise<void> {
  const root = path.resolve(bundlePath);

  // Collect and sort entries for deterministic ordering before opening streams.
  const entries = await fg('**/*', {
    cwd: root,
    dot: false,
    ignore: ['**/node_modules/**', '**/.git/**'],
    onlyFiles: true,
    followSymbolicLinks: false,
  });

  const output = createWriteStream(outputZipPath);
  const archive = archiver('zip', { zlib: { level: 6 } });

  archive.on('warning', (err: Error) => {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err;
  });

  // Pipe archive output to the write stream and wait for the write to finish.
  const finished = pipeline(archive, output);

  for (const rel of entries.sort()) {
    archive.file(path.join(root, rel), { name: rel });
  }

  await archive.finalize();
  await finished;
}

// ---------------------------------------------------------------------------
// Repomix output parser
// ---------------------------------------------------------------------------

/** XML node shape produced by fast-xml-parser for repomix XML output. */
interface RepomixXmlFile {
  '@_path'?: string;
  path?: string;
  '#text'?: string;
}

interface RepomixXmlRoot {
  repomix?: {
    files?: {
      file?: RepomixXmlFile | RepomixXmlFile[];
    };
  };
}

/**
 * Parses a repomix output file (XML or JSON) and returns the list of
 * source-file entries it contains.
 *
 * @param filePath  Path to the repomix output file.
 */
export async function parseRepomixFile(filePath: string): Promise<RepomixEntry[]> {
  const content = await fsPromises.readFile(filePath, 'utf8');
  const ext = path.extname(filePath).toLowerCase();

  if (ext === '.json') {
    return parseRepomixJson(content);
  }

  // Default: treat as XML (covers .xml and plain repomix-output files).
  return parseRepomixXml(content);
}

function parseRepomixXml(content: string): RepomixEntry[] {
  const parser = new XMLParser({
    ignoreAttributes: false,
    attributeNamePrefix: '@_',
    isArray: (_name, jpath) => jpath === 'repomix.files.file',
  });

  const root = parser.parse(content) as RepomixXmlRoot;
  const filesNode = root?.repomix?.files;
  if (!filesNode) return [];

  const fileNodes = Array.isArray(filesNode.file)
    ? filesNode.file
    : filesNode.file
    ? [filesNode.file]
    : [];

  return fileNodes
    .map(node => {
      const filePath = node['@_path'] ?? node.path;
      if (!filePath) return null;
      return { path: filePath } satisfies RepomixEntry;
    })
    .filter((e): e is RepomixEntry => e !== null);
}

/** Shape of a processed file entry in repomix JSON output. */
interface RepomixJsonFile {
  path?: string;
  content?: string;
  charCount?: number;
}

interface RepomixJsonRoot {
  files?: RepomixJsonFile[];
  processedFiles?: RepomixJsonFile[];
}

function parseRepomixJson(content: string): RepomixEntry[] {
  let root: RepomixJsonRoot;
  try {
    root = JSON.parse(content) as RepomixJsonRoot;
  } catch {
    return [];
  }

  const files = root.files ?? root.processedFiles ?? [];
  return files
    .map(f => {
      if (!f.path) return null;
      return {
        path: f.path,
        ...(f.charCount !== undefined ? { charCount: f.charCount } : {}),
      } satisfies RepomixEntry;
    })
    .filter((e): e is RepomixEntry => e !== null);
}

// ---------------------------------------------------------------------------
// Cleanup
// ---------------------------------------------------------------------------

/**
 * Removes cx-generated artefacts from a bundle folder.
 *
 * By default removes `manifest.json` and `SHA256SUMS`.
 * Pass `zipName` to also remove a specific ZIP file.
 *
 * @param bundlePath  Path to the bundle folder.
 * @param opts        Options controlling what is removed.
 */
export async function cleanupBundleGeneratedFiles(
  bundlePath: string,
  opts: { zipName?: string } = {},
): Promise<string[]> {
  const root = path.resolve(bundlePath);
  const candidates: string[] = ['manifest.json', 'SHA256SUMS'];
  if (opts.zipName) candidates.push(opts.zipName);

  const removed: string[] = [];
  for (const name of candidates) {
    const target = path.join(root, name);
    try {
      await fsPromises.unlink(target);
      removed.push(name);
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err;
      // File does not exist — silently skip.
    }
  }
  return removed;
}
